id: I80D94898
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T03:33:30+00:00'
last_modified: '2022-06-07T18:59:20.315812+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12079
  title: པཎ་ཆེན་བློ་བཟང་ཆོས་ཀྱི་རྒྱལ་མཚན་གྱི་གསུང་རྩོམ་ཐོར་བུ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A7FC:
      image_group_id: I1KG12081
      title: ''
      total_pages: 613
      order: 1
      base_file: A7FC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
