id: P003309
initial_creation_type: ocr
created_at: 1/04/2020
last_modified_at: 2021-12-17 10:54:12.707917
source_metadata:
  id: bdr:W1KG12079
  title: པཎ་ཆེན་བློ་བཟང་ཆོས་ཀྱི་རྒྱལ་མཚན་གྱི་གསུང་རྩོམ་ཐོར་བུ།
  author: ''
  volumes:
    f4c29ca08c8a4923b201cfa47212c738:
      image_group_id: I1KG12081
      title: ''
      volume_number: 1
      total_pages: 613
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
